"""add contract fields to equipo

Revision ID: fb21941638ba
Revises: b1c2d3e4f5a6
Create Date: 2026-06-26 11:22:04.798301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb21941638ba'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipos', sa.Column('tipo_adquisicion', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('equipos', sa.Column('contrato_pdf_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('equipos', sa.Column('hojas_servicio_urls', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipos', 'hojas_servicio_urls')
    op.drop_column('equipos', 'contrato_pdf_url')
    op.drop_column('equipos', 'tipo_adquisicion')
    # ### end Alembic commands ###
