"""Initial SQLModel Migration Ultimate Refined

Revision ID: fc59a6b78c4f
Revises: 
Create Date: 2026-04-11 20:44:30.896145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc59a6b78c4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('idx_os_equipo'), table_name='ordenes_servicio')
    # op.drop_index(op.f('idx_os_estado'), table_name='ordenes_servicio')
    # op.drop_index(op.f('idx_os_fecha'), table_name='ordenes_servicio')
    # op.drop_index(op.f('idx_os_tipo'), table_name='ordenes_servicio')
    # op.drop_index(op.f('numero_orden'), table_name='ordenes_servicio')
    # op.drop_index(op.f('idx_prev_equipo'), table_name='preventivos_programados')
    # op.drop_index(op.f('idx_prev_proxima'), table_name='preventivos_programados')
    # op.drop_index(op.f('idx_trazabilidad_equipo'), table_name='trazabilidad')
    # op.drop_index(op.f('idx_trazabilidad_fecha'), table_name='trazabilidad')
    op.alter_column('usuarios', 'matricula',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('usuarios', 'rol',
               existing_type=mysql.ENUM('biomedico', 'jefe_biomedica', 'jefe_conservacion', 'jefe_servicio', 'almacen', 'supervisor', 'admin', collation='utf8mb4_unicode_ci'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('usuarios', 'telefono',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('usuarios', 'whatsapp',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('usuarios', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.drop_index(op.f('matricula'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_matricula'), 'usuarios', ['matricula'], unique=True)
    op.alter_column('zonas_mapa', 'nombre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('zonas_mapa', 'codigo',
               existing_type=mysql.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('zonas_mapa', 'piso',
               existing_type=mysql.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('zonas_mapa', 'color_bg',
               existing_type=mysql.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'#1e293b'"))
    op.alter_column('zonas_mapa', 'color_borde',
               existing_type=mysql.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'#334155'"))
    op.alter_column('zonas_mapa', 'orden',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('zonas_mapa', 'activa',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    # op.drop_index(op.f('codigo'), table_name='zonas_mapa')
    op.create_index(op.f('ix_zonas_mapa_codigo'), 'zonas_mapa', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zonas_mapa_codigo'), table_name='zonas_mapa')
    op.create_index(op.f('codigo'), 'zonas_mapa', ['codigo'], unique=True)
    op.alter_column('zonas_mapa', 'activa',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('zonas_mapa', 'orden',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('zonas_mapa', 'color_borde',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'#334155'"))
    op.alter_column('zonas_mapa', 'color_bg',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'#1e293b'"))
    op.alter_column('zonas_mapa', 'piso',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('zonas_mapa', 'codigo',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('zonas_mapa', 'nombre',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_usuarios_matricula'), table_name='usuarios')
    op.create_index(op.f('matricula'), 'usuarios', ['matricula'], unique=True)
    op.alter_column('usuarios', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('usuarios', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.alter_column('usuarios', 'whatsapp',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               existing_nullable=True)
    op.alter_column('usuarios', 'telefono',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               existing_nullable=True)
    op.alter_column('usuarios', 'rol',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.ENUM('biomedico', 'jefe_biomedica', 'jefe_conservacion', 'jefe_servicio', 'almacen', 'supervisor', 'admin', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'matricula',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.create_index(op.f('idx_trazabilidad_fecha'), 'trazabilidad', ['fecha_movimiento'], unique=False)
    op.create_index(op.f('idx_trazabilidad_equipo'), 'trazabilidad', ['equipo_id'], unique=False)
    op.create_index(op.f('idx_prev_proxima'), 'preventivos_programados', ['proxima_ejecucion'], unique=False)
    op.create_index(op.f('idx_prev_equipo'), 'preventivos_programados', ['equipo_id'], unique=False)
    op.create_index(op.f('numero_orden'), 'ordenes_servicio', ['numero_orden'], unique=True)
    op.create_index(op.f('idx_os_tipo'), 'ordenes_servicio', ['tipo_mantenimiento'], unique=False)
    op.create_index(op.f('idx_os_fecha'), 'ordenes_servicio', ['fecha'], unique=False)
    op.create_index(op.f('idx_os_estado'), 'ordenes_servicio', ['estado'], unique=False)
    op.create_index(op.f('idx_os_equipo'), 'ordenes_servicio', ['equipo_id'], unique=False)
    # ### end Alembic commands ###
